baseURL: https://omfmartin.com
title: Olivier MF Martin
description: Olivier's data science blog and personal website. 
theme: PaperMod
paginate: 10

defaultContentLanguage: en

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: false

minify:
  disableXML: true
  minifyOutput: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

languages:
  en:
    contentDir: content/en
    languageName: English
    weight: 1
    DateFormat: "January 2, 2006"
    profileMode:
      enabled: true
      title: "Olivier MF Martin"
      subtitle: "Data Scientist | Bioinformatian"
      imageUrl: "cat.jpeg"
      imageTitle: "profile picture"
      imageWidth: 120
      imageHeight: 120
      buttons:
        - name: Blog
          url: "/posts"
        - name: Projects
          url: "/projects"
    menu:
      main:
        - identifier: posts
          name: Blog
          url: /posts/
          weight: 1
        - identifier: projects
          name: Projects
          url: /projects/
          weight: 2
        - identifier: about
          name: About
          url: /about-me
          weight: 3
        - identifier: search
          name: Search
          url: /search
          weight: 4
  es:
    contentDir: content/es
    languageName: Español
    weight: 2
    DateFormat: "02/01/2006"
    profileMode:
      enabled: true
      title: "Olivier MF Martin"
      subtitle: "Científico de Datos | Bioinformático"
      imageUrl: "cat.jpeg"
      imageTitle: "profile picture"
      imageWidth: 120
      imageHeight: 120
      buttons:
        - name: Blog
          url: "/es/posts"
        - name: Proyectos
          url: "/es/projects"
    menu:
      main:
        - identifier: posts
          name: Blog
          url: /es/posts/
          weight: 1
        - identifier: projects
          name: Projects
          url: /es/projects/
          weight: 2
        - identifier: about
          name: Sobre Mi
          url: /es/sobre-mi
          weight: 3
        - identifier: search
          name: Buscador
          url: /es/buscador
          weight: 4

params:
  description: "Olivier's Data Science Blog"
  author: "Olivier MF Martin"
  favicon: "/favicon.ico"

  socialIcons:
    - name: github
      url: "https://github.com/omfmartin"
    - name: linkedin
      url: "https://linkedin.com/in/omfmartin"
    - name: googlescholar
      url: "https://scholar.google.com/citations?user=GZ-cq-gAAAAJ"
    - name: medium
      url: "https://medium.com/@omfmartin"

  defaultTheme: auto # dark, light, auto
  disableThemeToggle: false
  displayFullLangName: true

  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  assets:
    favicon: "/favicon.ico"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: [ "title", "permalink", "summary", "content" ]

taxonomies:
  tag: tags


markup:
  goldmark:
    renderer:
      unsafe: true

services:
  googleAnalytics:
    ID: "G-PKR8VY4E8L"
